# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGjYseuLN_-y4Io5XQ_Yr8NWswiCePku
"""

# Rafli Maulana Putra  41823010058

def hitung_na(tugas, uts, uas):
    na = 0.25 * tugas + 0.35 * uts + 0.4 * uas
    return na

def penilaian(na):
  if na > 85:
    return "A"
  elif 80 < na <= 85:
    return "A-"
  elif 75 < na <= 80:
    return "B+"
  elif 70 < na <= 75:
    return "B"
  elif 65 < na <= 70:
    return "B-"
  elif 60 < na <= 65:
    return "C+"
  elif 55 < na <= 60:
    return "C"
  elif 50 < na <= 55:
    return "C-"
  elif 30 < na <= 50:
    return "D"
  else:
    return "E"

print("Selamat datang di Aplikasi perhitungan nilai Mahasiswa")
tugas = float(input("Silahkan Masukkan nilai Tugas Anda : "))
uts = float(input("Silahkan Masukkan nilai UTS Anda : "))
uas = float(input("Silahkan Masukkan nilai UAS Anda : "))

na = hitung_na (tugas, uts, uas)
nilai = penilaian (na)

print(f"Nilai akhir Anda : {na}")
print(f"Dalam Huruf : {nilai}")
